import { StyleSheet } from "react-native";

export const profileStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#f4efe7",
  },
  shell: {
    paddingHorizontal: 22,
    paddingTop: 24,
    paddingBottom: 28,
  },
  heroCard: {
    backgroundColor: "#0d141c",
    borderRadius: 30,
    padding: 20,
    borderWidth: 1,
    borderColor: "#192430",
  },
  eyebrow: {
    color: "#f7c948",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1.2,
    fontFamily: "NeueMontreal-Bold",
  },
  title: {
    color: "#f8f4ee",
    fontSize: 30,
    lineHeight: 34,
    marginTop: 10,
    fontFamily: "NeueMontreal-Bold",
  },
  subtitle: {
    color: "rgba(248, 244, 238, 0.84)",
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
    fontFamily: "NeueMontreal-Regular",
  },
  card: {
    marginTop: 24,
    backgroundColor: "#fbf7f1",
    borderRadius: 28,
    padding: 18,
    borderWidth: 1,
    borderColor: "#e9dccb",
  },
  label: {
    color: "#0d141c",
    fontSize: 14,
    marginBottom: 8,
    fontFamily: "NeueMontreal-Bold",
  },
  helperText: {
    color: "#6b7280",
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 12,
    fontFamily: "NeueMontreal-Regular",
  },
  input: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#e8ddd0",
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginBottom: 16,
    color: "#0d141c",
    fontFamily: "NeueMontreal-Regular",
  },
  roleRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 20,
  },
  roleChip: {
    flex: 1,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: "center",
    backgroundColor: "#efe5d8",
    borderWidth: 1,
    borderColor: "#e3d4c0",
  },
  roleChipSelected: {
    backgroundColor: "#0d141c",
    borderColor: "#0d141c",
  },
  roleChipText: {
    color: "#0d141c",
    fontSize: 14,
    fontFamily: "NeueMontreal-Bold",
  },
  roleChipTextSelected: {
    color: "#f8f4ee",
  },
  previewCard: {
    backgroundColor: "#fff7eb",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#f1dcc0",
    padding: 14,
    marginBottom: 18,
  },
  previewLabel: {
    color: "#8b5e3c",
    fontSize: 12,
    textTransform: "uppercase",
    fontFamily: "NeueMontreal-Bold",
  },
  previewValue: {
    color: "#0d141c",
    fontSize: 18,
    marginTop: 8,
    fontFamily: "NeueMontreal-Bold",
  },
  previewMeta: {
    color: "#5b6470",
    fontSize: 13,
    marginTop: 6,
    fontFamily: "NeueMontreal-Regular",
  },
  primaryButton: {
    backgroundColor: "#0d141c",
    borderRadius: 18,
    paddingVertical: 15,
    alignItems: "center",
  },
  primaryButtonDisabled: {
    opacity: 0.45,
  },
  primaryButtonText: {
    color: "#f8f4ee",
    fontSize: 15,
    fontFamily: "NeueMontreal-Bold",
  },
  secondaryAction: {
    color: "#0d141c",
    fontSize: 14,
    textAlign: "center",
    marginTop: 14,
    fontFamily: "NeueMontreal-Bold",
  },
});
