import { StyleSheet } from "react-native";

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f4efe7",
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  mapShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(11, 18, 26, 0.12)",
  },
  topBar: {
    position: "absolute",
    top: 18,
    left: 20,
    right: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  brand: {
    color: "#ffffff",
    fontSize: 30,
    fontFamily: "NeueMontreal-Bold",
  },
  brandSubtext: {
    color: "rgba(255,255,255,0.82)",
    fontSize: 14,
    marginTop: 4,
    fontFamily: "NeueMontreal-Regular",
  },
  liveBadge: {
    backgroundColor: "#f7c948",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
  },
  liveBadgeText: {
    color: "#1f2937",
    fontSize: 13,
    fontFamily: "NeueMontreal-Bold",
  },
  sheet: {
    marginTop: "auto",
    backgroundColor: "#f8f4ee",
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 22,
    height: "72%",
    minHeight: 420,
  },
  handle: {
    width: 42,
    height: 5,
    backgroundColor: "#d1d5db",
    alignSelf: "center",
    borderRadius: 999,
    marginBottom: 12,
  },
  eyebrow: {
    color: "#8b5e3c",
    fontSize: 12,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    fontFamily: "NeueMontreal-Bold",
  },
  title: {
    color: "#0d141c",
    fontSize: 28,
    lineHeight: 32,
    marginTop: 8,
    fontFamily: "NeueMontreal-Bold",
  },
  searchShell: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 2,
    marginTop: 14,
    borderWidth: 1,
    borderColor: "#eadfce",
  },
  searchInput: {
    fontSize: 16,
    color: "#0d141c",
    paddingVertical: 12,
    fontFamily: "NeueMontreal-Regular",
  },
  locationPicker: {
    marginTop: 12,
    backgroundColor: "#efe5d8",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  statusRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 14,
  },
  statusCard: {
    flex: 1,
    backgroundColor: "#efe5d8",
    borderRadius: 18,
    padding: 12,
  },
  statusLabel: {
    color: "#8b5e3c",
    fontSize: 12,
    marginBottom: 6,
    fontFamily: "NeueMontreal-Bold",
  },
  statusValue: {
    color: "#0d141c",
    fontSize: 14,
    lineHeight: 18,
    fontFamily: "NeueMontreal-Regular",
  },
  secondaryButton: {
    marginTop: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#0d141c",
    paddingVertical: 8,
    paddingHorizontal: 12,
    alignItems: "center",
    backgroundColor: "#f8f4ee",
  },
  secondaryButtonText: {
    color: "#0d141c",
    fontSize: 13,
    fontFamily: "NeueMontreal-Bold",
  },
  loadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 14,
  },
  loadingPanel: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 14,
  },
  loadingText: {
    color: "#4b5563",
    fontSize: 14,
    fontFamily: "NeueMontreal-Regular",
  },
  resultsList: {
    paddingTop: 14,
    paddingBottom: 6,
    gap: 10,
  },
  resultsWrapper: {
    flex: 1,
    minHeight: 0,
    marginTop: 8,
  },
  resultCard: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: "#efe3d3",
  },
  resultTitle: {
    color: "#0d141c",
    fontSize: 16,
    fontFamily: "NeueMontreal-Bold",
  },
  resultSubtitle: {
    color: "#6b7280",
    fontSize: 14,
    marginTop: 4,
    fontFamily: "NeueMontreal-Regular",
  },
  flowCard: {
    backgroundColor: "#1a2430",
    borderRadius: 22,
    padding: 16,
  },
  flowTitle: {
    color: "#f7c948",
    fontSize: 16,
    marginBottom: 10,
    fontFamily: "NeueMontreal-Bold",
  },
  flowStep: {
    color: "#f4f4f5",
    fontSize: 13,
    marginBottom: 6,
    fontFamily: "NeueMontreal-Regular",
  },
  emptyText: {
    color: "#6b7280",
    fontSize: 14,
    lineHeight: 20,
    paddingTop: 8,
    fontFamily: "NeueMontreal-Regular",
  },
  destinationCard: {
    backgroundColor: "#fff7eb",
    borderRadius: 20,
    padding: 14,
    marginTop: 14,
    borderWidth: 1,
    borderColor: "#f1dcc0",
  },
  destinationLabel: {
    color: "#8b5e3c",
    fontSize: 12,
    textTransform: "uppercase",
    fontFamily: "NeueMontreal-Bold",
  },
  destinationTitle: {
    color: "#0d141c",
    fontSize: 18,
    lineHeight: 24,
    marginTop: 8,
    fontFamily: "NeueMontreal-Bold",
  },
  changeLink: {
    color: "#0d141c",
    fontSize: 14,
    marginTop: 10,
    fontFamily: "NeueMontreal-Bold",
  },
  summaryRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 14,
  },
  summaryCard: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 12,
    borderWidth: 1,
    borderColor: "#efe3d3",
  },
  summaryValue: {
    color: "#0d141c",
    fontSize: 20,
    fontFamily: "NeueMontreal-Bold",
  },
  optionsContainer: {
    marginTop: 12,
    flex: 1,
    minHeight: 0,
  },
  optionsHeader: {
    marginBottom: 12,
  },
  optionsTitle: {
    color: "#0d141c",
    fontSize: 18,
    fontFamily: "NeueMontreal-Bold",
  },
  optionsSubtitle: {
    color: "#6b7280",
    fontSize: 13,
    fontFamily: "NeueMontreal-Regular",
    marginTop: 2,
  },
  optionsList: {
    flex: 1,
  },
  optionsListContent: {
    paddingBottom: 8,
    gap: 8,
  },
  optionsScrollArea: {
    flex: 1,
    minHeight: 140,
  },
  optionCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#efe3d3",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 72,
  },
  optionCardSelected: {
    borderColor: "#0d141c",
    borderWidth: 2,
    backgroundColor: "#f9fafb",
  },
  optionInfo: {
    flex: 1,
  },
  optionLeft: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  optionIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#f3eee5",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#e9dfd2",
  },
  optionIcon: {
    color: "#0d141c",
    fontSize: 12,
    letterSpacing: 0.6,
    fontFamily: "NeueMontreal-Bold",
  },
  optionTitle: {
    color: "#0d141c",
    fontSize: 16,
    fontFamily: "NeueMontreal-Bold",
  },
  optionDescription: {
    color: "#6b7280",
    fontSize: 13,
    marginTop: 4,
    fontFamily: "NeueMontreal-Regular",
  },
  optionPrice: {
    color: "#0d141c",
    fontSize: 18,
    fontFamily: "NeueMontreal-Bold",
    marginLeft: 12,
  },
  paymentRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: "#efe3d3",
    marginTop: 6,
    marginBottom: 4,
  },
  paymentLabel: {
    color: "#0d141c",
    fontSize: 14,
    fontFamily: "NeueMontreal-Bold",
  },
  promoLink: {
    color: "#8b5e3c",
    fontSize: 14,
    fontFamily: "NeueMontreal-Bold",
  },
  primaryButton: {
    backgroundColor: "#0d141c",
    borderRadius: 18,
    paddingVertical: 15,
    alignItems: "center",
    marginTop: 8,
  },
  primaryButtonText: {
    color: "#f8f4ee",
    fontSize: 15,
    fontFamily: "NeueMontreal-Bold",
  },
  stateScreen: {
    flex: 1,
    backgroundColor: "#f8f4ee",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 28,
  },
  stateTitle: {
    color: "#0d141c",
    fontSize: 28,
    textAlign: "center",
    marginTop: 18,
    fontFamily: "NeueMontreal-Bold",
  },
  stateText: {
    color: "#6b7280",
    fontSize: 15,
    lineHeight: 22,
    textAlign: "center",
    marginTop: 10,
    fontFamily: "NeueMontreal-Regular",
  },
});
