import { StyleSheet } from "react-native";

export const rideStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#f4efe7",
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  mapShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(11, 18, 26, 0.12)",
  },
  driverMarker: {
    alignItems: "center",
    justifyContent: "center",
  },
  driverPulse: {
    position: "absolute",
    width: 54,
    height: 54,
    borderRadius: 999,
    backgroundColor: "rgba(247, 201, 72, 0.18)",
  },
  driverMarkerCore: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#111827",
    borderWidth: 2,
    borderColor: "#f7c948",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#111827",
    shadowOpacity: 0.22,
    shadowRadius: 8,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: 6,
  },
  driverMarkerGlyph: {
    color: "#f8f4ee",
    fontSize: 15,
    fontFamily: "GeneralSans-Bold",
  },
  driverBubble: {
    marginTop: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "rgba(17, 24, 39, 0.88)",
  },
  driverBubbleText: {
    color: "#f8f4ee",
    fontSize: 11,
    fontFamily: "GeneralSans-Bold",
  },
  topBar: {
    position: "absolute",
    top: 18,
    left: 20,
    right: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  topBarTitle: {
    color: "#ffffff",
    fontSize: 28,
    fontFamily: "GeneralSans-Bold",
  },
  topBarSubtitle: {
    color: "rgba(255,255,255,0.82)",
    fontSize: 14,
    marginTop: 4,
    fontFamily: "GeneralSans-Regular",
  },
  badge: {
    backgroundColor: "#f7c948",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
  },
  badgeText: {
    color: "#1f2937",
    fontSize: 13,
    fontFamily: "GeneralSans-Bold",
  },
  card: {
    position: "absolute",
    bottom: 14,
    left: 16,
    right: 16,
    backgroundColor: "#f8f4ee",
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 16,
    elevation: 20,
    minHeight: 330,
    maxHeight: "52%",
  },
  optionsScrollArea: {
    flex: 1,
    minHeight: 0,
  },
  optionsScroll: {
    flex: 1,
  },
  cardScrollContent: {
    paddingBottom: 8,
  },
  handle: {
    width: 36,
    height: 4,
    backgroundColor: "#d1d5db",
    alignSelf: "center",
    borderRadius: 999,
    marginBottom: 12,
  },
  title: {
    color: "#111111",
    fontSize: 24,
    marginBottom: 2,
    fontFamily: "GeneralSans-Bold",
  },
  subtitle: {
    color: "#6b7280",
    fontSize: 13,
    marginBottom: 10,
    fontFamily: "GeneralSans-Regular",
  },
  optionsList: {
    gap: 8,
  },
  optionCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#efe3d3",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    minHeight: 68,
  },
  optionCardSelected: {
    borderWidth: 2,
    borderColor: "#0d141c",
    backgroundColor: "#ffffff",
  },
  optionLeft: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  optionIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: "#f3eee5",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#e9dfd2",
  },
  optionIcon: {
    fontSize: 12,
    color: "#0d141c",
    letterSpacing: 0.6,
    fontFamily: "GeneralSans-Bold",
  },
  optionIconImage: {
    width: 44,
    height: 44,
    resizeMode: "contain",
  },
  optionCopy: {
    flex: 1,
    paddingRight: 8,
  },
  optionTitle: {
    color: "#111111",
    fontSize: 16,
    fontFamily: "GeneralSans-Bold",
  },
  optionDescription: {
    color: "#6b7280",
    fontSize: 13,
    marginTop: 3,
    fontFamily: "GeneralSans-Regular",
  },
  optionFare: {
    color: "#111111",
    fontSize: 16,
    fontFamily: "GeneralSans-Bold",
  },
  sheetFooter: {
    paddingTop: 10,
    marginTop: 2,
    borderTopWidth: 1,
    borderTopColor: "#efe3d3",
  },
  primaryButton: {
    backgroundColor: "#0d141c",
    borderRadius: 18,
    paddingVertical: 13,
    alignItems: "center",
    marginTop: 10,
  },
  primaryButtonDisabled: {
    opacity: 0.6,
  },
  primaryButtonText: {
    color: "#f8f4ee",
    fontSize: 14,
    fontFamily: "GeneralSans-Bold",
  },
  back: {
    color: "#111111",
    marginTop: 10,
    textAlign: "center",
    fontSize: 13,
    fontFamily: "GeneralSans-Bold",
  },
  backDisabled: {
    opacity: 0.4,
  },
  contentCard: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 0,
    backgroundColor: "#f8f4ee",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 24,
    maxHeight: "58%",
  },
  contentCardScroll: {
    gap: 14,
  },
  statusSheet: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#f8f4ee",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 12,
    overflow: "hidden",
  },
  statusSheetHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#d5d9de",
    alignSelf: "center",
    marginBottom: 10,
  },
  statusTitle: {
    color: "#0d141c",
    fontSize: 20,
    lineHeight: 24,
    fontFamily: "GeneralSans-Bold",
  },
  statusSubtitle: {
    color: "#6b7280",
    fontSize: 14,
    lineHeight: 18,
    fontFamily: "GeneralSans-Regular",
    marginTop: 2,
  },
  etaRow: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  etaCaption: {
    color: "#6b7280",
    fontSize: 11,
    lineHeight: 14,
    letterSpacing: 1,
    textTransform: "uppercase",
    fontFamily: "GeneralSans-Bold",
    paddingBottom: 4,
  },
  etaValue: {
    color: "#0d141c",
    fontSize: 30,
    lineHeight: 36,
    fontFamily: "GeneralSans-Bold",
  },
  driverRow: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  driverAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#0d141c",
    alignItems: "center",
    justifyContent: "center",
  },
  driverAvatarText: {
    color: "#f8f4ee",
    fontSize: 15,
    fontFamily: "GeneralSans-Bold",
  },
  driverIdentity: {
    flex: 1,
  },
  driverNameLine: {
    flexDirection: "row",
    alignItems: "center",
  },
  driverName: {
    color: "#0d141c",
    fontSize: 16,
    fontFamily: "GeneralSans-Bold",
  },
  driverRating: {
    color: "#6b7280",
    fontSize: 13,
    fontFamily: "GeneralSans-Regular",
    marginLeft: 8,
  },
  driverVehicle: {
    color: "#6b7280",
    fontSize: 13,
    fontFamily: "GeneralSans-Regular",
    marginTop: 2,
  },
  actionsRow: {
    marginTop: 12,
    flexDirection: "row",
    gap: 10,
  },
  actionButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    height: 48,
    borderRadius: 16,
    backgroundColor: "rgba(17, 24, 39, 0.05)",
  },
  actionText: {
    color: "#0d141c",
    fontSize: 14,
    fontFamily: "GeneralSans-Bold",
  },
  fareRow: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  fareAmount: {
    color: "#0d141c",
    fontSize: 15,
    fontFamily: "GeneralSans-Bold",
  },
  fareDivider: {
    color: "#9ca3af",
    fontSize: 15,
    fontFamily: "GeneralSans-Regular",
  },
  fareLabel: {
    color: "#6b7280",
    fontSize: 15,
    fontFamily: "GeneralSans-Regular",
  },
  cancelRide: {
    color: "#dc2626",
    fontSize: 14,
    fontFamily: "GeneralSans-Bold",
    textAlign: "center",
    marginTop: 4,
    paddingVertical: 8,
  },
  searchingCenter: {
    alignItems: "center",
    paddingTop: 8,
  },
  searchingPulseWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#efe5d8",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  searchingTitle: {
    color: "#111111",
    fontSize: 22,
    lineHeight: 28,
    fontFamily: "GeneralSans-Bold",
    textAlign: "center",
  },
  searchingSubtitle: {
    color: "#6B7280",
    fontSize: 14,
    lineHeight: 20,
    fontFamily: "GeneralSans-Regular",
    textAlign: "center",
    marginTop: 6,
  },
  searchingFare: {
    color: "#0d141c",
    fontSize: 15,
    fontFamily: "GeneralSans-Bold",
    marginTop: 16,
  },
  sectionCard: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: "#efe3d3",
  },
  sectionLabel: {
    color: "#8b5e3c",
    fontSize: 12,
    textTransform: "uppercase",
    fontFamily: "GeneralSans-Bold",
  },
  sectionTitle: {
    color: "#0d141c",
    fontSize: 20,
    marginTop: 8,
    fontFamily: "GeneralSans-Bold",
  },
  sectionText: {
    color: "#4b5563",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
    fontFamily: "GeneralSans-Regular",
  },
  statsRow: {
    flexDirection: "row",
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: "#efe5d8",
    borderRadius: 18,
    padding: 14,
  },
  statValue: {
    color: "#0d141c",
    fontSize: 20,
    marginTop: 6,
    fontFamily: "GeneralSans-Bold",
  },
  compactStatsRow: {
    flexDirection: "row",
    gap: 12,
  },
  compactStat: {
    flex: 1,
    backgroundColor: "#efe5d8",
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  compactStatValue: {
    color: "#0d141c",
    fontSize: 18,
    marginTop: 6,
    fontFamily: "GeneralSans-Bold",
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#f2ebe2",
  },
  detailLabel: {
    color: "#6b7280",
    fontSize: 14,
    fontFamily: "GeneralSans-Regular",
  },
  detailValue: {
    color: "#0d141c",
    fontSize: 15,
    fontFamily: "GeneralSans-Bold",
  },
  timeline: {
    gap: 12,
  },
  timelineStep: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: "#efe3d3",
  },
  timelineTitle: {
    color: "#0d141c",
    fontSize: 16,
    fontFamily: "GeneralSans-Bold",
  },
  timelineText: {
    color: "#4b5563",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
    fontFamily: "GeneralSans-Regular",
  },
  stateScreen: {
    flex: 1,
    backgroundColor: "#f8f4ee",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 28,
  },
  stateTitle: {
    color: "#0d141c",
    fontSize: 28,
    textAlign: "center",
    marginTop: 18,
    fontFamily: "GeneralSans-Bold",
  },
  stateText: {
    color: "#6b7280",
    fontSize: 15,
    lineHeight: 22,
    textAlign: "center",
    marginTop: 10,
    fontFamily: "GeneralSans-Regular",
  },
});
